services:
  - type: web
    name: gold-price-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
